# Generated by Django 3.2 on 2024-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240203_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('moderator', 'Модератор'), ('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=150, verbose_name='Роль'),
        ),
    ]
