# Generated by Django 3.2 on 2024-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_score_review_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='count',
            new_name='score',
        ),
    ]
